---

- name: Ensure tools are installed
  apt:
    name: "{{ item }}"
    state: latest
    cache_valid_time: 86400
  with_items:
    - git
    - zip
    - unzip
    - g++
    - make
    - qgit
    - dos2unix
    - vim
    - firefox
    - chromium-browser
    - build-essential
