---

- name: Extract geoserver WAR
  get_url:
    url: http://build.geonode.org/geoserver/latest/geoserver-{{ geoserver_major_version }}.{{ geoserver_minor_version }}.x.war
    dest: /var/lib/tomcat8/webapps/geoserver.war

- name: restart tomcat
  service:
    name: tomcat8
    state: restarted

- name: add available site proxying /geoserver to geoserver in apache
  template:
    src: geoserver.conf
    dest: /etc/apache2/sites-available/geoserver.conf

- name: add symlink to enable geoserver site in apache
  file:
    path: /etc/apache2/sites-enabled/geoserver.conf
    state: link
    src: /etc/apache2/sites-available/geoserver.conf
  notify: restart apache

- name: Flush handlers to ensure geoserver war is deployed
  meta: flush_handlers

- name: Ensure tomcat8 owns all webapps files
  file:
    path: /var/lib/tomcat8/webapps/
    recurse: true
    owner: tomcat8
    group: tomcat8
  
- name: restart tomcat
  service:
    name: tomcat8
    state: restarted