---

- name: Ensure tomcat 8 is installed
  apt:
    name: "{{ item }}"
    state: latest
    cache_valid_time: 86400
  with_items:
    - default-jdk
    - tomcat8

- name: Configure memory for Tomcat
  template:
    src: setenv.sh
    dest: /usr/share/tomcat8/bin/setenv.sh

- name: Copy the catalania file to make sure bcprov*.jar is skipped at run-time
  template:
    src: catalina.properties
    dest: /var/lib/tomcat8/conf/catalina.properties