---
- name: repos enabled
  apt_repository: repo='{{item}}' state=present update_cache=no
  with_items:
    - ppa:libreoffice/ppa
    
- name: Install libreoffice
  apt:  pkg={{ item }} state=present update_cache=yes
  with_items:
    - libreoffice
    - libreoffice-headless

# - block:
#     - name: Find documents configuration
#       command: php occ config:app:get documents {{item.key}}
#       args:
#         chdir: '{{owncloud_path}}'
#       with_dict:
#         converter: local
#       register: owncloud__r_docs
#       changed_when: false
#       ignore_errors: yes

#     - name: Configure documents
#       command: php occ config:app:set documents {{item.item.key}} --value '{{item.item.value}}'
#       args:
#         chdir: '{{owncloud_path}}'
#       with_items: '{{owncloud__r_docs.results}}'
#       when: owncloud__r_docs | failed or item.stdout == '' or item.stdout_lines[0] != item.item.value

#   become: yes
#   become_user: '{{owncloud_user}}'
#   when: hostvars[owncloud_app_servers[0]].ansible_fqdn == ansible_fqdn
