---
- name: Install Sendmail (Debian)
  apt: pkg=sendmail state=installed
  when: ansible_os_family == "Debian"
  become: true

- name: Configure email server
  template: dest='{{owncloud_path}}/config/mail.config.php' src=mail.config.php.j2 mode=0640 owner='{{owncloud_user}}' group='{{owncloud_group}}'
