---
- name: Find if user_ldap is enabled
  command: php occ config:app:get user_ldap enabled
  args:
    chdir: '{{owncloud_path}}'
  register: owncloud__r_ldap
  changed_when: false
  ignore_errors: yes
  become: yes
  become_user: '{{owncloud_user}}'

- block:
    - name: Enable user_ldap
      command: php occ app:enable user_ldap
      args:
        chdir: '{{owncloud_path}}'
      when: owncloud__r_ldap | failed or owncloud__r_ldap.stdout_lines[0] == 'no'

    - name: Find if user_ldap has been initialized
      command: php occ ldap:show-config
      args:
        chdir: '{{owncloud_path}}'
      register: owncloud__r_user_init
      changed_when: false

    - name: Create empty user_ldap config
      command: php occ ldap:create-empty-config
      args:
        chdir: '{{owncloud_path}}'
      when: owncloud__r_user_init.stdout == ''

    - name: Find user_ldap configuration
      command: php occ config:app:get user_ldap {{item.key}}
      args:
        chdir: '{{owncloud_path}}'
      with_dict: '{{owncloud_user_ldap_config}}'
      register: owncloud__r_user
      changed_when: false

    - name: Configure user_ldap
      command: php occ ldap:set-config '' {{item.item.value[0]}} '{{item.item.value[1]}}'
      args:
        chdir: '{{owncloud_path}}'
      with_items: '{{owncloud__r_user.results}}'
      when: item.stdout == '' or item.stdout_lines[0] != item.item.value[1]

  become: yes
  become_user: '{{owncloud_user}}'
  when: owncloud_user_ldap_config != {}

- block:
    - name: Disable user_ldap
      command: php occ app:disable user_ldap
      args:
        chdir: '{{owncloud_path}}'
      when: owncloud__r_ldap | failed or owncloud__r_ldap.stdout_lines[0] == 'yes'

  become: yes
  become_user: '{{owncloud_user}}'
  when: owncloud_user_ldap_config == {}
