---

# Attempt to install via packaged download first if preferred.
# ------------------------------------------------------------------------------

- name: Prepare install path
  file:
    path: "{{ drush_install_path }}"
    state: directory
  when: drush_prefer_packaged_download
  sudo: true

- name: Check if requested Drush package file exists for download
  # Returns HTTP status code (string) of dynamically created file path
  command: curl -s -o /dev/null -w "%{http_code}" https://github.com/drush-ops/drush/releases/download/{{ drush_version }}/drush.phar
  register: drush_phar_http_code
  changed_when: false
  when: drush_prefer_packaged_download

- name: Download packaged Drush release
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/{{ drush_version }}/drush.phar
    dest: "{{ drush_install_path }}/drush"
    mode: "a+x"
  when: drush_prefer_packaged_download and drush_phar_http_code.stdout == "302"
  sudo: true

- name: Create drush symlink
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: link
  when: drush_prefer_packaged_download and drush_phar_http_code.stdout == "302"
  sudo: true


# Install via Composer if a packaged download didn't exist or is not preferred.
# ------------------------------------------------------------------------------

- include: global_drush_via_composer.yml
  when: drush_prefer_packaged_download == false or drush_phar_http_code.stdout != "302"
  sudo: true
