---

- name: Check for installed php-gdal
  stat:
    path: /usr/lib/php/20131226/gdal.so
  register: php_gdal_installed

- block:
  - name: clone php-gdal
    git:
      repo: https://github.com/geops/php5-gdal.git
      dest: /tmp/src/php5-gdal

  - name: phpize php5-gdal
    shell: phpize
    args:
      chdir: /tmp/src/php5-gdal

  - name: configure php5-gdal
    shell: ./configure
    args:
      chdir: /tmp/src/php5-gdal

  - name: make php5-gdal
    make:
      chdir: /tmp/src/php5-gdal

  - name: install php5-gdal
    make:
      chdir: /tmp/src/php5-gdal
      target: install
  
  when: php_gdal_installed.stat.exists == False

- name: create module config for php5-gdal
  template:
    src: gdal.ini
    dest: /etc/php/5.6/mods-available/gdal.ini

- name: enable php5-gdal module
  shell: phpenmod gdal
  args:
    creates: /etc/php/5.6/apache2/conf.d/20-gdal.ini
  notify: restart apache